#URL
cobalt.url=http://localhost:4000

whisper.url=http://0.0.0.0:9000/asr?output=json

vectorise.url=http://localhost:8000/vectorize

url=https://openrouter.ai/api/v1/chat/completions

model.name=mistralai/devstral-2512:free
api.key=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

#/Database-connection/

spring.datasource.url=jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username=documind
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

server.port=9190

management.endpoints.web.exposure.include=*