#URL
cobalt.url=http://localhost:4000

whisper.url=http://0.0.0.0:9000/asr?output=json

vectorise.url=http://localhost:8000/vectorize

model.name=nvidia/nemotron-3-super-120b-a12b:free
url=https://openrouter.ai/api/v1/chat/completions
api.key=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

#/Database-connection/

spring.datasource.url=jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username=documind
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

server.port=9190

management.endpoints.web.exposure.include=*


#https://rutube.ru/video/cc6dce76a054a314d8244e30ea433f26/