#URL
cobalt.url=http://localhost:4000

whisper.url=http://0.0.0.0:9000/asr?output=json

vectorise.url=http://localhost:8000/vectorize

api.key=

url=https://openrouter.ai/api/v1/chat/completions

model.name=minimax/minimax-m2:free

#/Database-connection/

spring.datasource.url=jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username=documind
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

