version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vectordb
    ports:
      - "5433:5432"