version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg16  # ← Используй pg16 вместо pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector_data: