version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vectordb
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data  # Том для данных БД (ОБЯЗАТЕЛЬНО!)
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Для init скриптов

volumes:
  pgvector_data:  # Объявляем том для данных