version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vectordb
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  tesseract-server:
    image: hertzg/tesseract-server:latest
    ports:
      - "8123:8884"
volumes:
  pgvector_data:

