DROP TABLE IF EXISTS vectors;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS vectors (
    id BIGSERIAL PRIMARY KEY,
    vector vector(384) NOT NULL,
    text TEXT NOT NULL,
    doc_id VARCHAR(36)
);