#DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5433/vectordb
spring.datasource.username=documind
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#FILE UPLOAD
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#API PROPERTIES
tesseract.datapath=src/main/resources/tessdata
vectorise.url=http://localhost:8000/vectorize

url=https://openrouter.ai/api/v1/chat/completions

#GPT MODELS
model.name=tngtech/deepseek-r1t2-chimera:free
api.key=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

management.endpoints.web.exposure.include=*
